language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - git clone https://github.com/joergen7/lang-util.git ~/common-lisp/lang-util

script:
  - cl -l fiveam
       -e '(setf fiveam:*on-error* t
                 fiveam:*on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(asdf:test-system :clcc)'

notifications:
  email:
    - joergen@cuneiform-lang.org
